{"tracks":{"href":"https://api.spotify.com/v1/search?query=beat+it&type=track&offset=0&limit=1",
           "items":[{"album":{"album_type":"album",
                              "artists":[{"external_urls":{"spotify":"https://open.spotify.com/artist/3fMbdgg4jU18AjLCKBhRSm"},
                              "href":"https://api.spotify.com/v1/artists/3fMbdgg4jU18AjLCKBhRSm",
                              "id":"3fMbdgg4jU18AjLCKBhRSm",
                              "name":"Michael Jackson",
                              "type":"artist",
                              "uri":"spotify:artist:3fMbdgg4jU18AjLCKBhRSm"}],
                                "available_markets":["AD","AE","AL","AR","AT","AU","BA","BE","BG","BH","BO","BR","BY","CA","CH","CL","CO","CR","CY","CZ","DE","DK","DO","DZ","EC","EE","EG","ES","FI","FR","GB","GR","GT","HK","HN","HR","HU","ID","IE","IL","IN","IS","IT","JO","JP","KW","KZ","LB","LI","LT","LU","LV","MA","MC","MD","ME","MK","MT","MX","MY","NI","NL","NO","NZ","OM","PA","PE","PH","PL","PS","PT","PY","QA","RO","RS","RU","SA","SE","SG","SI","SK","SV","TH","TN","TR","TW","UA","US","UY","VN","XK","ZA"],"external_urls":{"spotify":"https://open.spotify.com/album/1C2h7mLntPSeVYciMRTF4a"},"href":"https://api.spotify.com/v1/albums/1C2h7mLntPSeVYciMRTF4a","id":"1C2h7mLntPSeVYciMRTF4a","images":[{"height":640,"url":"https://i.scdn.co/image/ab67616d0000b2734121faee8df82c526cbab2be","width":640},{"height":300,"url":"https://i.scdn.co/image/ab67616d00001e024121faee8df82c526cbab2be","width":300},{"height":64,"url":"https://i.scdn.co/image/ab67616d000048514121faee8df82c526cbab2be","width":64}],"name":"Thriller 25 Super Deluxe Edition","release_date":"1982-11-30","release_date_precision":"day","total_tracks":30,"type":"album","uri":"spotify:album:1C2h7mLntPSeVYciMRTF4a"},"artists":[{"external_urls":{"spotify":"https://open.spotify.com/artist/3fMbdgg4jU18AjLCKBhRSm"},"href":"https://api.spotify.com/v1/artists/3fMbdgg4jU18AjLCKBhRSm","id":"3fMbdgg4jU18AjLCKBhRSm","name":"Michael Jackson","type":"artist","uri":"spotify:artist:3fMbdgg4jU18AjLCKBhRSm"}],"available_markets":["AD","AE","AL","AR","AT","AU","BA","BE","BG","BH","BO","BR","BY","CA","CH","CL","CO","CR","CY","CZ","DE","DK","DO","DZ","EC","EE","EG","ES","FI","FR","GB","GR","GT","HK","HN","HR","HU","ID","IE","IL","IN","IS","IT","JO","JP","KW","KZ","LB","LI","LT","LU","LV","MA","MC","MD","ME","MK","MT","MX","MY","NI","NL","NO","NZ","OM","PA","PE","PH","PL","PS","PT","PY","QA","RO","RS","RU","SA","SE","SG","SI","SK","SV","TH","TN","TR","TW","UA","US","UY","VN","XK","ZA"],
                                "disc_number":1,
                                "duration_ms":258040,
                                "explicit":false,
                                "external_ids":{"isrc":"USSM19902990"},
                                "external_urls":{"spotify":"https://open.spotify.com/track/1OOtq8tRnDM8kG2gqUPjAj"},
                                "href":"https://api.spotify.com/v1/tracks/1OOtq8tRnDM8kG2gqUPjAj",
                                "id":"1OOtq8tRnDM8kG2gqUPjAj",
                                "is_local":false,
                                "name":"Beat It - Single Version",
                                "popularity":78,
                                "preview_url":"https://p.scdn.co/mp3-preview/4901df6e0f8bf6ce93e08df7d98a50e220c45799?cid=3da84aa1068b4f46bd133c1927bccf89",
                                "track_number":5,
                                "type":"track",
            "uri":"spotify:track:1OOtq8tRnDM8kG2gqUPjAj"}],
            "limit":1,
            "next":"https://api.spotify.com/v1/search?query=beat+it&type=track&offset=1&limit=1",
            "offset":0,
            "previous":null,
            "total":32623}}

##### This is want ('/test-1)

{'album_group': 'album',
 'album_type': 'album',
  'artists': [{'external_urls': {'spotify': 'https://open.spotify.com/artist/2WX2uTcsvV5OnS0inACecP'},
                                 'href': 'https://api.spotify.com/v1/artists/2WX2uTcsvV5OnS0inACecP', 
                                 'id': '2WX2uTcsvV5OnS0inACecP', 'name': 'Birdy', 'type': 'artist', 
                                 'uri': 'spotify:artist:2WX2uTcsvV5OnS0inACecP'}],
 'available_markets': ['US'],
 'external_urls': {'spotify': 'https://open.spotify.com/album/5wNnopxjgSKVvHTIcBpV8Q'}, 
 'href': 'https://api.spotify.com/v1/albums/5wNnopxjgSKVvHTIcBpV8Q', 
 'id': '5wNnopxjgSKVvHTIcBpV8Q', 
 'images': [{'height': 640, 'url': 'https://i.scdn.co/image/ab67616d0000b273f67ea4e620f14bd9dad994e5', 'width': 640}, 
            {'height': 300, 'url': 'https://i.scdn.co/image/ab67616d00001e02f67ea4e620f14bd9dad994e5', 'width': 300}, 
            {'height': 64, 'url': 'https://i.scdn.co/image/ab67616d00004851f67ea4e620f14bd9dad994e5', 'width': 64}], 
 'name': 'Beautiful Lies', 
 'release_date': '2016-03-25', 
 'release_date_precision': 'day', 
 'total_tracks': 14, 
 'type': 'album', 
 'uri': 'spotify:album:5wNnopxjgSKVvHTIcBpV8Q'}